version: "2"
services:
  app:
    container_name: berriesandgoods
    restart: always
    build: .
    network_mode: "bridge"
    command: "pipenv run bash -c ./start.sh"
    volumes:
      - .:/usr/src/app
    ports:
      - "80:8000"
  test:
    container_name: berriesandgoods_test
    restart: always
    build: .
    command:
      bash -c "pipenv run coverage run -m pytest --ignore=data -vv
      --disable-warnings; pipenv run coverage report -m; pipenv run coverage
      html"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: berries
      POSTGRES_PASSWORD: berries
      POSTGRES_DB: berry_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
