# Generated by Django 2.1.3 on 2018-11-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berry',
            fields=[
                ('idberry', models.IntegerField(primary_key=True, serialize=False)),
                ('nameberry', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'berry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Berrytype',
            fields=[
                ('idberrytype', models.IntegerField(primary_key=True, serialize=False)),
                ('nameberrytype', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'berrytype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('idgoods', models.IntegerField(primary_key=True, serialize=False)),
                ('namegoods', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goodstype',
            fields=[
                ('idgoodstype', models.IntegerField(primary_key=True, serialize=False)),
                ('namegoodstype', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'goodstype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('idorders', models.IntegerField(primary_key=True, serialize=False)),
                ('payment', models.BooleanField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idproduct', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producttype',
            fields=[
                ('idproducttype', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'producttype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idusers', models.IntegerField(primary_key=True, serialize=False)),
                ('admin', models.BooleanField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
